language: php

php:
    - '7.1'

git:
    depth: 10

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - phpenv config-rm xdebug.ini
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - composer self-update --no-interaction

install:
    - composer update --prefer-dist --optimize-autoloader

script:
    - vendor/bin/phpcs -p --standard=PSR2 --extensions=php src
    - vendor/bin/php-cs-fixer fix --dry-run -v --diff --config=.php_cs.php
    - vendor/bin/phpspec run
    - vendor/bin/behat --suite=acceptance
    - vendor/bin/behat --suite=integration
